#!/bin/bash
# backend/server_entrypoint.sh — Server.dockerfile container entrypoint
# 1) Run builderMasterServer.py at operation time (produces server.secrets, server.env, torrc)
# 2) Source secrets (no placeholders — values generated by the builder)
# 3) Start Tor hidden services + nginx reverse-proxy to uvicorn
# 4) Start uvicorn FastAPI master server (bound to localhost; *.onion via Tor)

set -euo pipefail

TORRC="${HOST_TOR_CONFIG_TORRC:-/mnt/myssd/LucidTops/torrc}"
SECRETS_ENV="${SECRETS_ENV_FILE:-/mnt/myssd/LucidTops/secrets.env}"
SERVER_SECRETS="${SERVER_SECRETS_FILE:-/mnt/myssd/LucidTops/secrets/server.secrets}"
CONFIG_SECRETS="${CONFIG_SECRETS_FILE:-/mnt/myssd/LucidTops/secrets/config.secrets}"
OPERATIONS_SECRETS="${OPERATIONS_SECRETS_FILE:-/mnt/myssd/LucidTops/secrets/operations.secrets}"
SECRETS_DIR="${SECRETS_DIR:-/mnt/myssd/LucidTops/secrets}"
LUCID_TOPS_ROOT="${LUCID_TOPS_ROOT:-/mnt/myssd/LucidTops}"
RUN_BUILDER_ON_START="${RUN_BUILDER_ON_START:-true}"

mkdir -p "${LUCID_TOPS_ROOT}" \
         "${SECRETS_DIR}" \
         "${LUCID_TOPS_ROOT}/configs" \
         "${LUCID_TOPS_ROOT}/logs" \
         "${LUCID_TOPS_ROOT}/data/tor" \
         /app/var/lib/tor/lucid_server \
         /app/var/lib/tor/lucid_portal \
         /app/var/lib/tor/lucid_node \
         /app/run/lucid/onion

_source_secrets_if_present() {
  local path="$1"
  if [ -f "${path}" ]; then
    set -a
    # shellcheck disable=SC1090
    source "${path}"
    set +a
  fi
}

if [ "${RUN_BUILDER_ON_START}" = "true" ] || [ ! -f "${SERVER_SECRETS}" ]; then
  echo "entrypoint: running builderMasterServer.py (operation-time server.secrets generation)"
  cd /app/backend
  python builderMasterServer.py
fi

_source_secrets_if_present "${SECRETS_ENV}"
_source_secrets_if_present "${SERVER_SECRETS}"
_source_secrets_if_present "${CONFIG_SECRETS}"
_source_secrets_if_present "${OPERATIONS_SECRETS}"

MONGODB_SECRETS="${MONGODB_SECRETS_FILE:-${SECRETS_DIR}/mongodb.secrets}"
BLOCKCHAIN_SECRETS="${BLOCKCHAIN_SECRETS_FILE:-${SECRETS_DIR}/blockchain.secrets}"
PAYMENTS_SECRETS="${PAYMENTS_SECRETS_FILE:-${SECRETS_DIR}/payments.secrets}"
_source_secrets_if_present "${MONGODB_SECRETS}"
_source_secrets_if_present "${BLOCKCHAIN_SECRETS}"
_source_secrets_if_present "${PAYMENTS_SECRETS}"

if [ ! -f "${SERVER_SECRETS}" ]; then
  echo "entrypoint: error — server.secrets was not produced at ${SERVER_SECRETS}" >&2
  exit 2
fi

BIND_HOST="${MASTER_SERVER_BIND_HOST:-127.0.0.1}"
PORT="${MASTER_SERVER_PORT:-8080}"

NGINX_CONF="/etc/nginx/conf.d/lucid-uvicorn.conf"
cat > "${NGINX_CONF}" <<EOF
server {
    listen 80;
    server_name _;
    location / {
        proxy_pass http://${BIND_HOST}:${PORT};
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

if [ -f "${TORRC}" ]; then
  echo "entrypoint: starting tor with ${TORRC}"
  tor -f "${TORRC}" &
  sleep 5
  for svc in lucid_server lucid_portal lucid_node; do
    hostname_file="/app/var/lib/tor/${svc}/hostname"
    if [ -f "${hostname_file}" ]; then
      onion="$(tr -d '[:space:]' < "${hostname_file}")"
      echo "${onion}" > "/app/run/lucid/onion/${svc}.onion"
    fi
  done
  # Re-run builder after onion hostnames exist so server.secrets gets real Tor URLs
  cd /app/backend
  python builderMasterServer.py
  _source_secrets_if_present "${SERVER_SECRETS}"
  _source_secrets_if_present "${SECRETS_ENV_FILE:-${SECRETS_ENV}}"
else
  echo "entrypoint: warning — torrc not found at ${TORRC}; API will not be reachable via *.onion"
fi

echo "entrypoint: starting nginx reverse-proxy -> ${BIND_HOST}:${PORT}"
nginx

cd /app/backend
exec python -m uvicorn main:create_app \
  --factory \
  --host "${BIND_HOST}" \
  --port "${PORT}" \
  --log-level "${LOG_LEVEL:-info}"
